package com.cegb03.metodos.SistEcLin;

import com.cegb03.metodos.SistEcLin.GaussSeidelCode;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author cegb03
 */
public class SistematEcuacionesLinealesFrame extends javax.swing.JFrame {
    
    File gaussianFile;    // Archivo específico para Eliminación Gaussiana
    File jacobiFile;        // Archivo específico para Jacobi
    File gaussSeidelFile;   // Archivo específico para Gauss-Seidel
    
    private Double[][] matrixAlge;
    private Double[][] matrixAAlge;
    private Double[] matrixBAlge;
    private Double[] matrixXAlge;
    private Double[][] matrixIte;
    private Double[][] matrixAIte;
    private Double[] matrixBIte;
    private Double[] matrixXIte;
    
    // Matrices específicas para Jacobi
    private Double[][] matrixJacobi;
    private Double[][] matrixAJacobi;
    private Double[] matrixBJacobi;
    
    // Matrices específicas para Gauss-Seidel
    private Double[][] matrixGaussSeidel;
    private Double[][] matrixAGaussSeidel;
    private Double[] matrixBGaussSeidel;
    
    private int filasAlge = 0;
    private int columnasAlge = 0;
    private int filasIte = 0;
    private int columnasIte = 0;
    
    // Dimensiones específicas para cada método
    private int filasJacobi = 0;
    private int columnasJacobi = 0;
    private int filasGaussSeidel = 0;
    private int columnasGaussSeidel = 0;
    
    private Double tolerancia = 0.0;
    private Double factorRelajacion;

    /**
     * Creates new form SistematEcuacionesLinealesFrame
     */
    public SistematEcuacionesLinealesFrame() {
        initComponents();
        btnCargarArchivoAlgebraico.setEnabled(false);
        btnCargarArchivoIterativo.setEnabled(false);
        btnCalcular.setEnabled(false);
        txtTol.setEnabled(false);
        txtRelajacion.setEnabled(false);
        
        // Cambiar el texto del botón para reflejar su nueva funcionalidad unificada
        btnCargarArchivoIterativo.setText("Cargar Archivos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarArchivoAlgebraico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResultados = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtTol = new javax.swing.JTextField();
        txtRelajacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCheckEliGauss = new javax.swing.JCheckBox();
        btnCheckJacobi = new javax.swing.JCheckBox();
        btnCheckGaussSeidel = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnCargarArchivoIterativo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarArchivoAlgebraico.setText("Cargar Archivo Alge");
        btnCargarArchivoAlgebraico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoAlgebraicoActionPerformed(evt);
            }
        });

        jLabel1.setText("Metodos de Sistema de Ecuaciones Algebraicas Lineales y Sistema de Ecuaciones Lineales Iterativos");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtAResultados.setEditable(false);
        txtAResultados.setColumns(20);
        txtAResultados.setRows(5);
        jScrollPane1.setViewportView(txtAResultados);

        jLabel2.setText("Ingrese la tolerancia *");

        txtTol.setText("0.001");
        txtTol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTolActionPerformed(evt);
            }
        });

        txtRelajacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelajacionActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese la ralajacion(opcional)");

        btnCheckEliGauss.setText("Eliminacion Gaussiana");
        btnCheckEliGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEliGaussActionPerformed(evt);
            }
        });

        btnCheckJacobi.setText("Jacobi");
        btnCheckJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckJacobiActionPerformed(evt);
            }
        });

        btnCheckGaussSeidel.setText("Gauss-Seidel");
        btnCheckGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckGaussSeidelActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnCargarArchivoIterativo.setText("Cargar Archivo Itera");
        btnCargarArchivoIterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoIterativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCheckEliGauss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckJacobi)
                .addGap(141, 141, 141)
                .addComponent(btnCheckGaussSeidel)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 70, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRelajacion)
                            .addComponent(txtTol, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargarArchivoAlgebraico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargarArchivoIterativo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckEliGauss)
                    .addComponent(btnCheckJacobi)
                    .addComponent(btnCheckGaussSeidel))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarArchivoAlgebraico)
                    .addComponent(btnCargarArchivoIterativo))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRelajacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoAlgebraicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoAlgebraicoActionPerformed
        loadMatrixFromFile();
        //System.out.println("loadMatrixFromFile() fin");
    }//GEN-LAST:event_btnCargarArchivoAlgebraicoActionPerformed
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtTolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTolActionPerformed

    private void txtRelajacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelajacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelajacionActionPerformed

    private void btnCheckEliGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEliGaussActionPerformed
        // Habilitar el botón de carga unificado si algún método está seleccionado
        boolean algunMetodoSeleccionado = btnCheckEliGauss.isSelected() || 
                                         btnCheckJacobi.isSelected() || 
                                         btnCheckGaussSeidel.isSelected();
        btnCargarArchivoIterativo.setEnabled(algunMetodoSeleccionado);
        
        // Mantener compatibilidad con el botón separado si existe
        btnCargarArchivoAlgebraico.setEnabled(btnCheckEliGauss.isSelected());       
    }//GEN-LAST:event_btnCheckEliGaussActionPerformed

    private void btnCheckJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckJacobiActionPerformed
        // Verificar si algún método está seleccionado para habilitar la carga
        boolean algunMetodoSeleccionado = btnCheckEliGauss.isSelected() || 
                                         btnCheckJacobi.isSelected() || 
                                         btnCheckGaussSeidel.isSelected();
        boolean activoTolerancia = btnCheckJacobi.isSelected() || btnCheckGaussSeidel.isSelected();
        
        btnCargarArchivoIterativo.setEnabled(algunMetodoSeleccionado);
        txtTol.setEnabled(activoTolerancia);
    }//GEN-LAST:event_btnCheckJacobiActionPerformed

    private void btnCheckGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckGaussSeidelActionPerformed
        // Verificar si algún método está seleccionado para habilitar la carga
        boolean algunMetodoSeleccionado = btnCheckEliGauss.isSelected() || 
                                         btnCheckJacobi.isSelected() || 
                                         btnCheckGaussSeidel.isSelected();
        boolean activoTolerancia = btnCheckJacobi.isSelected() || btnCheckGaussSeidel.isSelected();
        
        btnCargarArchivoIterativo.setEnabled(algunMetodoSeleccionado);
        txtTol.setEnabled(activoTolerancia);
        txtRelajacion.setEnabled(btnCheckGaussSeidel.isSelected());
    }//GEN-LAST:event_btnCheckGaussSeidelActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        LocalDateTime now = LocalDateTime.now();

        // Formatear la hora actual
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedNow = now.format(formatter);
        // Mostrar la hora actual en el campo de texto
        if(txtAResultados.getText().isBlank())
            txtAResultados.setText("\tHora: " + formattedNow);
        else
            txtAResultados.setText(txtAResultados.getText()+"\n\n"+"\tHora: " + formattedNow);
        
        
        if(btnCheckEliGauss.isSelected()){
            EliminacionGaussianaCode egc = new EliminacionGaussianaCode(matrixAAlge, matrixBAlge, matrixXAlge, filasAlge, columnasAlge - 1);
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Eliminacion Gaussiana:\n"+egc.eliminar()); // Puedes modificar esta línea para otro procesamiento
            System.out.println("Fin Elimnacion");
        }
        if(btnCheckJacobi.isSelected()){
            Double[][] matrixA_Jacobi;
            Double[] matrixB_Jacobi;
            int filasJacobiActual, columnasJacobiActual;
            
            // Si ambos métodos están seleccionados, usar matrices específicas
            if (btnCheckJacobi.isSelected() && btnCheckGaussSeidel.isSelected()) {
                // Verificar si la matriz de Jacobi está cargada
                if (matrixAJacobi == null || matrixBJacobi == null) {
                    txtAResultados.setText(txtAResultados.getText()+
                        "\n❌ Error: No se ha cargado matriz para el método de Jacobi.\n" +
                        "   Por favor, cargue un archivo para Jacobi antes de calcular.\n");
                    return; // Salir sin procesar Jacobi
                }
                matrixA_Jacobi = matrixAJacobi;
                matrixB_Jacobi = matrixBJacobi;
                filasJacobiActual = filasJacobi;
                columnasJacobiActual = columnasJacobi;
            } else {
                matrixA_Jacobi = matrixAIte;
                matrixB_Jacobi = matrixBIte;
                filasJacobiActual = filasIte;
                columnasJacobiActual = columnasIte;
            }
            
            // Verificar dominancia diagonal antes de ejecutar Jacobi
            boolean esDominante = verificarDominanciaDiagonal(matrixA_Jacobi, filasJacobiActual);
            
            if (!esDominante) {
                txtAResultados.setText(txtAResultados.getText()+"\n"+"        Jacobi:\n"+
                    imprimir(filasJacobiActual, columnasJacobiActual - 1, matrixA_Jacobi, matrixB_Jacobi)+
                    "\nTolerancia usada: "+tolerancia+
                    "\n⚠️  ADVERTENCIA: La matriz NO es diagonalmente dominante.\n" +
                    "   El método de Jacobi puede no converger.\n" +
                    "   Recomendación: Use Eliminación Gaussiana para este sistema.\n");
            }
            
            JacobiCode j = new JacobiCode(matrixA_Jacobi, matrixB_Jacobi, filasJacobiActual, tolerancia);
            String resultado = j.eliminar();
            
            if (resultado.contains("Infinity") || resultado.contains("NaN")) {
                txtAResultados.setText(txtAResultados.getText()+
                    "\n❌ Error: El método de Jacobi no converge para esta matriz.\n" +
                    "   Motivo: La matriz no cumple las condiciones de convergencia.\n" +
                    "   Solución: Use Eliminación Gaussiana en su lugar.\n");
            } else {
                txtAResultados.setText(txtAResultados.getText()+"\n"+resultado);
            }

            System.out.println("Fin Jacobi");
        }
        if(btnCheckGaussSeidel.isSelected()){
            Double[][] matrixA_GaussSeidel;
            Double[] matrixB_GaussSeidel;
            int filasGaussSeidelActual, columnasGaussSeidelActual;
            
            // Si ambos métodos están seleccionados, usar matrices específicas
            if (btnCheckJacobi.isSelected() && btnCheckGaussSeidel.isSelected()) {
                // Verificar si la matriz de Gauss-Seidel está cargada
                if (matrixAGaussSeidel == null || matrixBGaussSeidel == null) {
                    txtAResultados.setText(txtAResultados.getText()+
                        "\n❌ Error: No se ha cargado matriz para el método de Gauss-Seidel.\n" +
                        "   Por favor, cargue un archivo para Gauss-Seidel antes de calcular.\n");
                    return; // Salir sin procesar Gauss-Seidel
                }
                matrixA_GaussSeidel = matrixAGaussSeidel;
                matrixB_GaussSeidel = matrixBGaussSeidel;
                filasGaussSeidelActual = filasGaussSeidel;
                columnasGaussSeidelActual = columnasGaussSeidel;
            } else {
                matrixA_GaussSeidel = matrixAIte;
                matrixB_GaussSeidel = matrixBIte;
                filasGaussSeidelActual = filasIte;
                columnasGaussSeidelActual = columnasIte;
            }
            
            // Verificar dominancia diagonal antes de ejecutar Gauss-Seidel
            boolean esDominante = verificarDominanciaDiagonal(matrixA_GaussSeidel, filasGaussSeidelActual);
            
            if (!esDominante) {
                txtAResultados.setText(txtAResultados.getText()+"\n"+"        Gauss Seidel:\n"+
                    imprimir(filasGaussSeidelActual, columnasGaussSeidelActual - 1, matrixA_GaussSeidel, matrixB_GaussSeidel)+
                    "\nTolerancia usada: "+tolerancia+
                    "\n⚠️  ADVERTENCIA: La matriz NO es diagonalmente dominante.\n" +
                    "   El método de Gauss-Seidel puede no converger.\n" +
                    "   Recomendación: Use Eliminación Gaussiana para este sistema.\n");
            }
            
            GaussSeidelCode gs = new GaussSeidelCode(matrixA_GaussSeidel, matrixB_GaussSeidel, filasGaussSeidelActual, tolerancia);
            String resultado;
            
            if ( txtRelajacion.getText().isBlank() ){
                resultado = gs.sinRelajacion();
                if (resultado.contains("Infinity") || resultado.contains("NaN")) {
                    txtAResultados.setText(txtAResultados.getText()+
                        "\n❌ Error: El método de Gauss-Seidel no converge para esta matriz.\n" +
                        "   Motivo: La matriz no cumple las condiciones de convergencia.\n" +
                        "   Solución: Use Eliminación Gaussiana en su lugar.\n");
                } else {
                    txtAResultados.setText(txtAResultados.getText()+"\n"+"        Gauss Seidel:\n"+
                        imprimir(filasGaussSeidelActual, columnasGaussSeidelActual - 1, matrixA_GaussSeidel, matrixB_GaussSeidel)+
                        "\nTolerancia usada: "+tolerancia+"\n"+resultado);
                }
            }else{
                factorRelajacion = Double.valueOf(txtRelajacion.getText());
                resultado = gs.conRelajacion(factorRelajacion);
                if (resultado.contains("Infinity") || resultado.contains("NaN")) {
                    txtAResultados.setText(txtAResultados.getText()+
                        "\n❌ Error: El método de Gauss-Seidel con relajación no converge para esta matriz.\n" +
                        "   Motivo: La matriz no cumple las condiciones de convergencia.\n" +
                        "   Solución: Use Eliminación Gaussiana en su lugar.\n");
                } else {
                    txtAResultados.setText(txtAResultados.getText()+"\n"+"        Gauss Seidel:\n"+
                        imprimir(filasGaussSeidelActual, columnasGaussSeidelActual - 1, matrixA_GaussSeidel, matrixB_GaussSeidel)+
                        "\nTolerancia usada: "+tolerancia+"\nY la variable de relajacion: "+factorRelajacion+"\n"+resultado);
                }
            }
            System.out.println("Fin Gauss-Seidel");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCargarArchivoIterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoIterativoActionPerformed
        tolerancia = Double.valueOf(txtTol.getText());
        
        // Determinar qué métodos están seleccionados
        boolean jacobiSelected = btnCheckJacobi.isSelected();
        boolean gaussSeidelSelected = btnCheckGaussSeidel.isSelected();
        boolean gaussianaSelected = btnCheckEliGauss.isSelected();
        
        // Contar cuántos métodos iterativos están seleccionados
        int metodosIterativos = (jacobiSelected ? 1 : 0) + (gaussSeidelSelected ? 1 : 0);
        int totalMetodos = metodosIterativos + (gaussianaSelected ? 1 : 0);
        
        if (totalMetodos >= 2) {
            // Si hay 2 o más métodos seleccionados, usar archivos separados
            loadSeparateFilesForIterativeMethods();
        } else if (totalMetodos == 1) {
            // Si solo hay un método seleccionado, usar archivo único
            loadMatrixFromFile();
        } else {
            // No hay métodos seleccionados
            JOptionPane.showMessageDialog(this, "Por favor, seleccione al menos un método antes de cargar archivo.", 
                                        "Ningún método seleccionado", JOptionPane.WARNING_MESSAGE);
        }
        //System.out.println("loadMatrixFromFile() fin");
    }//GEN-LAST:event_btnCargarArchivoIterativoActionPerformed

    private void loadSeparateFilesForIterativeMethods() {
        boolean jacobiLoaded = false;
        boolean gaussSeidelLoaded = false;
        boolean gaussianaLoaded = false;
        
        // Verificar qué métodos están seleccionados
        boolean jacobiSelected = btnCheckJacobi.isSelected();
        boolean gaussSeidelSelected = btnCheckGaussSeidel.isSelected();
        boolean gaussianaSelected = btnCheckEliGauss.isSelected();
        
        // Cargar archivo para Eliminación Gaussiana si está seleccionado
        if (gaussianaSelected) {
            JOptionPane.showMessageDialog(this, "Selecciona el archivo para el método de Eliminación Gaussiana", 
                                        "Archivo para Eliminación Gaussiana", JOptionPane.INFORMATION_MESSAGE);
            gaussianaLoaded = loadFileForMethod("Gaussiana");
        }
        
        // Cargar archivo para Jacobi si está seleccionado
        if (jacobiSelected) {
            JOptionPane.showMessageDialog(this, "Selecciona el archivo para el método de Jacobi", 
                                        "Archivo para Jacobi", JOptionPane.INFORMATION_MESSAGE);
            jacobiLoaded = loadFileForMethod("Jacobi");
        }
        
        // Cargar archivo para Gauss-Seidel si está seleccionado
        if (gaussSeidelSelected) {
            JOptionPane.showMessageDialog(this, "Selecciona el archivo para el método de Gauss-Seidel", 
                                        "Archivo para Gauss-Seidel", JOptionPane.INFORMATION_MESSAGE);
            gaussSeidelLoaded = loadFileForMethod("GaussSeidel");
        }
        // Verificar el estado final y habilitar el botón calcular según corresponda
        if (jacobiLoaded || gaussSeidelLoaded || gaussianaLoaded) {
            btnCalcular.setEnabled(true);
            
            // Mostrar resumen del estado
            String resumen = "\n=== Estado de carga de archivos ===";
            
            if (gaussianaSelected) {
                if (gaussianaLoaded) {
                    resumen += "\n✓ Eliminación Gaussiana: Matriz cargada correctamente";
                } else {
                    resumen += "\n✗ Eliminación Gaussiana: No disponible (carga cancelada o falló)";
                }
            }
            
            if (jacobiSelected) {
                if (jacobiLoaded) {
                    resumen += "\n✓ Jacobi: Matriz cargada correctamente";
                } else {
                    resumen += "\n✗ Jacobi: No disponible (carga cancelada o falló)";
                }
            }
            
            if (gaussSeidelSelected) {
                if (gaussSeidelLoaded) {
                    resumen += "\n✓ Gauss-Seidel: Matriz cargada correctamente";
                } else {
                    resumen += "\n✗ Gauss-Seidel: No disponible (carga cancelada o falló)";
                }
            }
            
            resumen += "\n================================\n";
            txtAResultados.setText(txtAResultados.getText() + resumen);
        } else {
            // Si todos fallaron, no habilitar el botón
            txtAResultados.setText(txtAResultados.getText() + "\nNo se cargó ningún archivo. El botón Calcular permanece deshabilitado.");
        }
    }
    
    private boolean loadFileForMethod(String method) {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Matriz " + method, "dat", "txt");
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        File selectedFile=null;
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
             selectedFile = fileChooser.getSelectedFile();
            
            if (method.equals("Jacobi")) {
                jacobiFile = selectedFile;
                return loadMatrixForJacobi(selectedFile);
            } else if (method.equals("GaussSeidel")) {
                gaussSeidelFile = selectedFile;
                return loadMatrixForGaussSeidel(selectedFile);
            } else if (method.equals("Gaussiana")) {
                gaussianFile = selectedFile;
                return loadMatrixForGaussiana(selectedFile);
            }
        }
        return false;
    }
    
    private boolean loadMatrixForJacobi(File file) {
        try {
            readMatrixFromFileForMethod(file, "Jacobi");
            separarMatricesAB(columnasJacobi, filasJacobi, matrixAJacobi, matrixJacobi, matrixBJacobi);
            
            if (matrixAJacobi != null && matrixBJacobi != null) {
                // No mostrar mensaje aquí, se manejará en el resumen
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Error al procesar la matriz para Jacobi.");
                txtAResultados.setText(txtAResultados.getText() + "\nError al procesar la matriz para Jacobi.");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar archivo para Jacobi: " + e.getMessage());
            return false;
        }
    }
    
    private boolean loadMatrixForGaussSeidel(File file) {
        try {
            readMatrixFromFileForMethod(file, "GaussSeidel");
            separarMatricesAB(columnasGaussSeidel, filasGaussSeidel, matrixAGaussSeidel, matrixGaussSeidel, matrixBGaussSeidel);
            
            if (matrixAGaussSeidel != null && matrixBGaussSeidel != null) {
                // No mostrar mensaje aquí, se manejará en el resumen
                // El botón se habilitará en loadSeparateFilesForIterativeMethods()
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Error al procesar la matriz para Gauss-Seidel.");
                txtAResultados.setText(txtAResultados.getText() + "\nError al procesar la matriz para Gauss-Seidel.");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar archivo para Gauss-Seidel: " + e.getMessage());
            return false;
        }
    }
    
    private boolean loadMatrixForGaussiana(File file) {
        try {
            readMatrixFromFileForMethod(file, "Gaussiana");
            separarMatricesAB(columnasAlge, filasAlge, matrixAAlge, matrixAlge, matrixBAlge);
            
            if (matrixAAlge != null && matrixBAlge != null) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Error al procesar la matriz para Eliminación Gaussiana.");
                txtAResultados.setText(txtAResultados.getText() + "\nError al procesar la matriz para Eliminación Gaussiana.");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar archivo para Eliminación Gaussiana: " + e.getMessage());
            return false;
        }
    }

    private void separarMatricesAB(int columnas, int filas, Double[][] matrixA, Double[][] matrix, Double[] matrixB){
        int columns = columnas - 1; // Restar 1 para la matriz A (excluyendo la columna de términos independientes)
        
        // Validar que tenemos al menos 2 columnas (una para A y una para B)
        if (columnas < 2) {
            System.err.println("Error: La matriz debe tener al menos 2 columnas");
            return;
        }
        
        //System.out.println("columnas " + columnas + " filas " + filas + " columns " + columns);
        for (int i = 0; i < filas; i++) {
            // Copiar elementos de la matriz A
            for (int j = 0; j < columns && j < matrix[i].length; j++) {
                matrixA[i][j] = matrix[i][j];
            }
            // Copiar el término independiente (última columna)
            if (matrix[i].length >= columnas) {
                matrixB[i] = matrix[i][columnas - 1]; // Usar columnas - 1 para acceder a la última columna real
            } else {
                System.err.println("Error: Fila " + i + " no tiene suficientes columnas");
                matrixB[i] = 0.0; // Valor por defecto
            }
        }
        //imprimir();
    }
    
    private void loadMatrixFromFile() {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Matriz Gaussiana", "dat", "txt");
        fileChooser.setFileFilter(filter);

        // Establecer el directorio actual como el del proyecto
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                readMatrixFromFile(selectedFile);
                if(txtAResultados.getText().isBlank()){
                    if(btnCheckEliGauss.isSelected()){
                        // Separar la matriz en A (coeficientes) y B (términos independientes)
                        separarMatricesAB(columnasAlge, filasAlge, matrixAAlge, matrixAlge, matrixBAlge);
                        
                        if(matrixAAlge != null && matrixBAlge != null){
                            btnCalcular.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(null, "Error al procesar la matriz ingresada(lecura/sepracion).");
                            txtAResultados.setText(txtAResultados.getText()+"\nError al procesar la matriz ingresada(lecura/sepracion)."); // Puedes modificar esta línea para otro procesamiento
                        }
                    }
                    if(btnCheckJacobi.isSelected() || btnCheckGaussSeidel.isSelected()){
                        separarMatricesAB(columnasIte, filasIte, matrixAIte, matrixIte, matrixBIte);
                        System.out.println("matriz recuperda:\n"+printMatrix(matrixAIte)+"\nFin Matriz recuperada.");
                        //txtAResultados.setText(txtAResultados.getText()+"\n"+printMatrix(matrixAIte)); // Puedes modificar esta línea para otro procesamiento
                        if(matrixAIte != null && matrixBIte != null){
                            btnCalcular.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(null, "Error al procesar la matriz ingresada(lecura/sepracion).");
                            txtAResultados.setText(txtAResultados.getText()+"\nError al procesar la matriz ingresada(lecura/sepracion)."); // Puedes modificar esta línea para otro procesamiento
                        }
                    }
                }
                else{
                    if(btnCheckEliGauss.isSelected()){
                        // Separar la matriz en A (coeficientes) y B (términos independientes)
                        separarMatricesAB(columnasAlge, filasAlge, matrixAAlge, matrixAlge, matrixBAlge);
                        
                        if(matrixAAlge != null && matrixBAlge != null){
                            btnCalcular.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(null, "Error al procesar la matriz ingresada(lecura/sepracion).");
                            txtAResultados.setText(txtAResultados.getText()+"\nError al procesar la matriz ingresada(lecura/sepracion)."); // Puedes modificar esta línea para otro procesamiento
                        }
                    }
                    if(btnCheckJacobi.isSelected() || btnCheckGaussSeidel.isSelected()){
                        separarMatricesAB(columnasIte, filasIte, matrixAIte, matrixIte, matrixBIte);
                        System.out.println("matriz recuperda:\n"+printMatrix(matrixAIte)+"\nFin Matriz recuperada.");
                        //txtAResultados.setText(txtAResultados.getText()+"\n"+printMatrix(matrixAIte)); // Puedes modificar esta línea para otro procesamiento
                        if(matrixAIte != null && matrixBIte != null){
                            btnCalcular.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(null, "Error al procesar la matriz ingresada(lecura/sepracion).");
                            txtAResultados.setText(txtAResultados.getText()+"\nError al procesar la matriz ingresada(lecura/sepracion)."); // Puedes modificar esta línea para otro procesamiento
                        }
                    }
                    
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private void readMatrixFromFile(File file) throws IOException {
        List<Double[]> filas = new ArrayList<>();
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                
                // Limpiar la línea: remover caracteres no numéricos excepto espacios, puntos, signos y comas
                line = line.replaceAll("[^0-9.\\-+\\s,=]", " ");
                
                // Reemplazar múltiples espacios con uno solo
                line = line.replaceAll("\\s+", " ");
                
                // Dividir por espacios y/o comas
                String[] tokens = line.split("[\\s,=]+");
                
                List<Double> numerosEncontrados = new ArrayList<>();
                
                for (String token : tokens) {
                    token = token.trim();
                    if (!token.isEmpty()) {
                        try {
                            // Intentar convertir cada token a Double
                            if (token.matches("-?\\d+(\\.\\d+)?")) {
                                Double numero = Double.valueOf(token);
                                numerosEncontrados.add(numero);
                                //System.out.println("Número válido procesado: '" + token + "' -> " + numero);
                            } else {
                                System.out.println("Token rechazado (no es número): '" + token + "'");
                            }
                        } catch (NumberFormatException e) {
                            // Ignorar tokens que no se puedan convertir a números
                            System.out.println("Token ignorado: '" + token + "'");
                        }
                    }
                }

                if (!numerosEncontrados.isEmpty()) {
                    Double[] fila = numerosEncontrados.toArray(new Double[0]);
                    filas.add(fila);
                    //System.out.println("Fila procesada con " + fila.length + " números: " + Arrays.toString(fila));
                }
            }
        }

        // Convertir lista a matriz
        if (filas.isEmpty()) {
            throw new IOException("No se encontraron datos válidos en el archivo");
        }
        
        // Encontrar el número máximo de columnas
        int maxColumnas = 0;
        for (Double[] fila : filas) {
            maxColumnas = Math.max(maxColumnas, fila.length);
        }
        
        // Normalizar todas las filas al mismo tamaño rellenando con ceros
        for (int i = 0; i < filas.size(); i++) {
            if (filas.get(i).length < maxColumnas) {
                Double[] filaOriginal = filas.get(i);
                Double[] filaNormalizada = new Double[maxColumnas];
                
                // Copiar elementos existentes
                System.arraycopy(filaOriginal, 0, filaNormalizada, 0, filaOriginal.length);
                
                // Rellenar con ceros los elementos faltantes
                for (int j = filaOriginal.length; j < maxColumnas; j++) {
                    filaNormalizada[j] = 0.0;
                }
                
                filas.set(i, filaNormalizada);
                System.out.println("Fila " + (i+1) + " normalizada de " + filaOriginal.length + " a " + maxColumnas + " columnas");
            }
        }
        
        Double[][] matrizCarga = new Double[filas.size()][maxColumnas];
        for (int i = 0; i < filas.size(); i++) {
            matrizCarga[i] = filas.get(i);
        }
        
        if(btnCheckEliGauss.isSelected()){
            filasAlge = filas.size();
            columnasAlge = filas.get(0).length;
            this.matrixAlge = new Double[filasAlge][columnasAlge];
            this.matrixAAlge = new Double[filasAlge][columnasAlge - 1]; // Solo coeficientes A
            this.matrixBAlge = new Double[filasAlge];
            this.matrixXAlge = new Double[filasAlge];

            //System.out.println("Matriz Carga: \n"+printMatrix(matrizCarga));
            
            // Validar dimensiones antes de copiar
            for (int i = 0; i < filasAlge; i++) {
                int columnasToCopy = Math.min(matrizCarga[i].length, columnasAlge);
                System.arraycopy(matrizCarga[i], 0, this.matrixAlge[i], 0, columnasToCopy);
            }
            
            //System.out.println("Matriz Alge: \n"+printMatrix(matrixAlge));
        }
        if(btnCheckGaussSeidel.isSelected() || btnCheckJacobi.isSelected()){
            filasIte = filas.size();
            columnasIte = filas.get(0).length;
            this.matrixIte = new Double[filasIte][columnasIte];
            this.matrixAIte = new Double[filasIte][columnasIte - 1]; // Solo coeficientes A
            this.matrixBIte = new Double[filasIte];

            // Validar dimensiones antes de copiar
            for (int i = 0; i < filasIte; i++) {
                int columnasToCopy = Math.min(matrizCarga[i].length, columnasIte);
                System.arraycopy(matrizCarga[i], 0, this.matrixIte[i], 0, columnasToCopy);
            }
        }
    }

    private void readMatrixFromFileForMethod(File file, String method) throws IOException {
        List<Double[]> filas = new ArrayList<>();
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                
                // Limpiar la línea: remover caracteres no numéricos excepto espacios, puntos, signos y comas
                line = line.replaceAll("[^0-9.\\-+\\s,=]", " ");
                
                // Reemplazar múltiples espacios con uno solo
                line = line.replaceAll("\\s+", " ");
                
                // Dividir por espacios y/o comas
                String[] tokens = line.split("[\\s,=]+");
                
                List<Double> numerosEncontrados = new ArrayList<>();
                
                for (String token : tokens) {
                    token = token.trim();
                    if (!token.isEmpty()) {
                        try {
                            // Intentar convertir cada token a Double
                            if (token.matches("-?\\d+(\\.\\d+)?")) {
                                Double numero = Double.valueOf(token);
                                numerosEncontrados.add(numero);
                            }
                        } catch (NumberFormatException e) {
                            // Ignorar tokens que no se puedan convertir a números
                        }
                    }
                }

                if (!numerosEncontrados.isEmpty()) {
                    Double[] fila = numerosEncontrados.toArray(new Double[0]);
                    filas.add(fila);
                }
            }
        }

        // Convertir lista a matriz
        if (filas.isEmpty()) {
            throw new IOException("No se encontraron datos válidos en el archivo");
        }
        
        // Encontrar el número máximo de columnas
        int maxColumnas = 0;
        for (Double[] fila : filas) {
            maxColumnas = Math.max(maxColumnas, fila.length);
        }
        
        // Normalizar todas las filas al mismo tamaño rellenando con ceros
        for (int i = 0; i < filas.size(); i++) {
            if (filas.get(i).length < maxColumnas) {
                Double[] filaOriginal = filas.get(i);
                Double[] filaNormalizada = new Double[maxColumnas];
                
                // Copiar elementos existentes
                System.arraycopy(filaOriginal, 0, filaNormalizada, 0, filaOriginal.length);
                
                // Rellenar con ceros los elementos faltantes
                for (int j = filaOriginal.length; j < maxColumnas; j++) {
                    filaNormalizada[j] = 0.0;
                }
                
                filas.set(i, filaNormalizada);
            }
        }
        
        Double[][] matrizCarga = new Double[filas.size()][maxColumnas];
        for (int i = 0; i < filas.size(); i++) {
            matrizCarga[i] = filas.get(i);
        }
        
        // Asignar a las matrices específicas del método
        if (method.equals("Jacobi")) {
            filasJacobi = filas.size();
            columnasJacobi = filas.get(0).length;
            this.matrixJacobi = new Double[filasJacobi][columnasJacobi];
            this.matrixAJacobi = new Double[filasJacobi][columnasJacobi - 1];
            this.matrixBJacobi = new Double[filasJacobi];
            
            // Copiar datos a la matriz de Jacobi
            for (int i = 0; i < filasJacobi; i++) {
                int columnasToCopy = Math.min(matrizCarga[i].length, columnasJacobi);
                System.arraycopy(matrizCarga[i], 0, this.matrixJacobi[i], 0, columnasToCopy);
            }
        } else if (method.equals("GaussSeidel")) {
            filasGaussSeidel = filas.size();
            columnasGaussSeidel = filas.get(0).length;
            this.matrixGaussSeidel = new Double[filasGaussSeidel][columnasGaussSeidel];
            this.matrixAGaussSeidel = new Double[filasGaussSeidel][columnasGaussSeidel - 1];
            this.matrixBGaussSeidel = new Double[filasGaussSeidel];
            
            // Copiar datos a la matriz de Gauss-Seidel
            for (int i = 0; i < filasGaussSeidel; i++) {
                int columnasToCopy = Math.min(matrizCarga[i].length, columnasGaussSeidel);
                System.arraycopy(matrizCarga[i], 0, this.matrixGaussSeidel[i], 0, columnasToCopy);
            }
        } else if (method.equals("Gaussiana")) {
            filasAlge = filas.size();
            columnasAlge = filas.get(0).length;
            this.matrixAlge = new Double[filasAlge][columnasAlge];
            this.matrixAAlge = new Double[filasAlge][columnasAlge - 1];
            this.matrixBAlge = new Double[filasAlge];
            this.matrixXAlge = new Double[filasAlge];
            
            // Copiar datos a la matriz de Eliminación Gaussiana
            for (int i = 0; i < filasAlge; i++) {
                int columnasToCopy = Math.min(matrizCarga[i].length, columnasAlge);
                System.arraycopy(matrizCarga[i], 0, this.matrixAlge[i], 0, columnasToCopy);
            }
        }
    }

    private String printMatrix(Double[][] matrix) {
        String matriz;
        matriz = "";
        for (Double[] row : matrix) {
            for (Double value : row) {
                matriz += (value + " ");
            }
            matriz += "\n";
        }
        return matriz;
    }
    
    /**
     * Verifica si una matriz es diagonalmente dominante
     * Condición: |A[i][i]| >= Σ|A[i][j]| para j≠i, para todas las filas
     */
    private boolean verificarDominanciaDiagonal(Double[][] matrix, int filas) {
        for (int i = 0; i < filas; i++) {
            double diagonal = Math.abs(matrix[i][i]);
            double sumaFila = 0.0;
            
            for (int j = 0; j < matrix[i].length; j++) {
                if (i != j) {
                    sumaFila += Math.abs(matrix[i][j]);
                }
            }
            
            System.out.println("Fila " + (i+1) + ": |" + matrix[i][i] + "| = " + diagonal + 
                             " vs suma=" + sumaFila + " -> " + (diagonal >= sumaFila ? "✓" : "✗"));
            
            if (diagonal < sumaFila) {
                return false;
            }
        }
        return true;
    }
    
    public String imprimir(int filas, int columnas, Double[][] matrixA, Double[] matrixB) {
        String matrizImpresa = "";
        matrizImpresa += ("Impresion de matrices A y b separadas\n");
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++)
                matrizImpresa += (matrixA[i][j] + " ");
            matrizImpresa += ("| " + matrixB[i]+"\n");
        }
        matrizImpresa += "\n";
        return matrizImpresa;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCargarArchivoAlgebraico;
    private javax.swing.JButton btnCargarArchivoIterativo;
    private javax.swing.JCheckBox btnCheckEliGauss;
    private javax.swing.JCheckBox btnCheckGaussSeidel;
    private javax.swing.JCheckBox btnCheckJacobi;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAResultados;
    private javax.swing.JTextField txtRelajacion;
    private javax.swing.JTextField txtTol;
    // End of variables declaration//GEN-END:variables
}
