package com.cegb03.metodos.LocRaices;

import com.cegb03.metodos.LocRaices.Abiertos.NewtonRapsonCode;
import com.cegb03.metodos.LocRaices.Abiertos.PuntoFijoCode;
import com.cegb03.metodos.LocRaices.Abiertos.SecanteCode;
import com.cegb03.metodos.LocRaices.Cerrados.*;
import com.cegb03.metodos.calculos.Derivar;
import com.cegb03.metodos.calculos.Graficador;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.NumberAxis;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;



/**
 *
 * @author cegb03
 */
public class LocRaicesFrame extends javax.swing.JFrame {
    
    private String funX;
    private Double a;
    private Double b;
    private Double tolerancia;
    private String funY;
    private String derivadaAux;
    private Double xn;
    private double paso = 0.01; // Ajusta el paso si es necesario
    private final Derivar derivacion = new Derivar();

    /**
     * Creates new form Biseccion
     */
    public LocRaicesFrame() {
        initComponents();
        txtFunF.setEnabled(false);
        txtFunY.setEnabled(false);
        txtVarXNuevo.setEnabled(false);
        txtVarA.setEnabled(false);
        txtVarB.setEnabled(false);
        txtVarTol.setEnabled(false);
        txtFunY.setBackground(Color.orange);
        txtVarXNuevo.setBackground(Color.orange);
        txtVarA.setBackground(Color.blue);
        txtVarB.setBackground(Color.blue);
        txtFunF.setBackground(Color.gray);
        txtVarTol.setBackground(Color.gray);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPPrincial = new javax.swing.JPanel();
        jPInput = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblInFunF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFunF = new javax.swing.JTextField();
        txtVarA = new javax.swing.JTextField();
        txtVarB = new javax.swing.JTextField();
        txtVarTol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResultados = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();
        btnCheckBiseccion = new javax.swing.JCheckBox();
        btnChecRegulaFalsi = new javax.swing.JCheckBox();
        btnChecNewtonRapson = new javax.swing.JCheckBox();
        btnChecPuntoFijo = new javax.swing.JCheckBox();
        btnChecSecante = new javax.swing.JCheckBox();
        lblInFunG = new javax.swing.JLabel();
        txtFunY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtVarXNuevo = new javax.swing.JTextField();
        jPGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Metodo Loc Raices General");

        lblInFunF.setText("Ingrese el valor f(x): ");

        jLabel3.setText("Ingrese el valor a: ");

        jLabel4.setText("Ingrese el valor b: ");

        jLabel5.setText("Ingrese el valor error tolerable: ");

        txtFunF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFunFActionPerformed(evt);
            }
        });

        txtAResultados.setEditable(false);
        txtAResultados.setColumns(20);
        txtAResultados.setRows(5);
        jScrollPane1.setViewportView(txtAResultados);

        jLabel6.setText("Resultados:");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular Racies");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnCheckBiseccion.setText("Biseccion");
        btnCheckBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBiseccionActionPerformed(evt);
            }
        });

        btnChecRegulaFalsi.setText("RegulaFalsi");
        btnChecRegulaFalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecRegulaFalsiActionPerformed(evt);
            }
        });

        btnChecNewtonRapson.setText("Newton Rapson");
        btnChecNewtonRapson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecNewtonRapsonActionPerformed(evt);
            }
        });

        btnChecPuntoFijo.setText("Punto Fijo");
        btnChecPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecPuntoFijoActionPerformed(evt);
            }
        });

        btnChecSecante.setText("Secante");
        btnChecSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecSecanteActionPerformed(evt);
            }
        });

        lblInFunG.setText("Ingrese el valor g(x) derivada de F: ");

        txtFunY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFunYActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese el valor a(Xnuevo): ");

        javax.swing.GroupLayout jPInputLayout = new javax.swing.GroupLayout(jPInput);
        jPInput.setLayout(jPInputLayout);
        jPInputLayout.setHorizontalGroup(
            jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInputLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnCalcular)
                .addGap(64, 64, 64)
                .addComponent(btnGraficar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPInputLayout.createSequentialGroup()
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInputLayout.createSequentialGroup()
                        .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPInputLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblInFunF)
                                                .addComponent(jLabel3))
                                            .addGap(90, 90, 90)
                                            .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtFunF)
                                                .addComponent(txtVarA, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                        .addGroup(jPInputLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(25, 25, 25)
                                            .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtVarB)
                                                .addComponent(txtVarTol)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInputLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(btnChecPuntoFijo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                            .addComponent(btnChecNewtonRapson)
                                            .addGap(36, 36, 36)
                                            .addComponent(btnChecSecante)))
                                    .addGroup(jPInputLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel6))))
                            .addGroup(jPInputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblInFunG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFunY, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInputLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblTitulo))
                            .addGroup(jPInputLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnCheckBiseccion)
                                .addGap(47, 47, 47)
                                .addComponent(btnChecRegulaFalsi)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInputLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(52, 52, 52)
                                .addComponent(txtVarXNuevo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInputLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPInputLayout.setVerticalGroup(
            jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInFunF)
                    .addComponent(txtFunF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVarTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckBiseccion)
                    .addComponent(btnChecRegulaFalsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChecPuntoFijo)
                    .addComponent(btnChecSecante)
                    .addComponent(btnChecNewtonRapson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInFunG)
                    .addComponent(txtFunY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVarXNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular)
                    .addComponent(btnGraficar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPGrafico.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPGraficoLayout = new javax.swing.GroupLayout(jPGrafico);
        jPGrafico.setLayout(jPGraficoLayout);
        jPGraficoLayout.setHorizontalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        jPGraficoLayout.setVerticalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPPrincialLayout = new javax.swing.GroupLayout(jPPrincial);
        jPPrincial.setLayout(jPPrincialLayout);
        jPPrincialLayout.setHorizontalGroup(
            jPPrincialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincialLayout.createSequentialGroup()
                .addComponent(jPInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPrincialLayout.setVerticalGroup(
            jPPrincialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        btnCalcular.setEnabled(false);
        btnCalcular.setBackground(Color.red);
        btnVolver.setEnabled(false);
        btnVolver.setBackground(Color.red);
        boolean metodosAbiertos = btnChecPuntoFijo.isSelected() || btnChecNewtonRapson.isSelected() || btnChecSecante.isSelected();
        boolean metodosCerrados = btnChecRegulaFalsi.isSelected()|| btnCheckBiseccion.isSelected();
        if(metodosCerrados){
            if (txtVarA.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor del limite inferior a");
            if (txtVarB.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor del limite inferior b");
            if (txtVarTol.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor del error tolerable");
            if (txtFunF.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor de la Funcion F(x)");
            
            funX = txtFunF.getText();
            tolerancia = Double.valueOf(txtVarTol.getText());
            funX = txtFunF.getText();
            System.out.println("funX "+funX);
            a = Double.valueOf(txtVarA.getText());
            b = Double.valueOf(txtVarB.getText());
        }
        if(metodosAbiertos){
            if (txtFunF.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor de la Funcion F(x)");
            if (txtFunY.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor de la Funcion G(x)");
            if (txtVarXNuevo.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor de inicio XNuevo");
            if (txtVarTol.getText() == null)
                JOptionPane.showMessageDialog(this, "Ingrese el valor del error tolerable");
            
            funX = txtFunF.getText();
            funY = txtFunY.getText();
            System.out.println( "funX " + funX + " \nfunY " + funY );
            xn = Double.valueOf(txtVarXNuevo.getText());
            tolerancia = Double.valueOf(txtVarTol.getText());
        }
        // TODO Corregir
        // Obtener la hora actual
        LocalDateTime now = LocalDateTime.now();

        // Formatear la hora actual
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedNow = now.format(formatter);
        // Mostrar la hora actual en el campo de texto
        if(txtAResultados.getText().isBlank())
            txtAResultados.setText("\tHora: " + formattedNow);
        else
            txtAResultados.setText(txtAResultados.getText()+"\n\n"+"\tHora: " + formattedNow);
        
        if(btnCheckBiseccion.isSelected()){
            BiseccionCode lcRaiz = new BiseccionCode(a, b, tolerancia, funX);
            graficarFuncionMetodosCerrados();
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Biseccion:\n"+lcRaiz.calcularRaiz());
        }
        if(btnChecRegulaFalsi.isSelected()){
            RegulaFalsiCode lcRaiz = new RegulaFalsiCode(a, b, tolerancia, funX);
            graficarFuncionMetodosCerrados();
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Regula Falsi:\n"+lcRaiz.calcularRaiz());
        }
        if(btnChecPuntoFijo.isSelected()){
            derivadaAux = derivacion.derivar(funX);
            if (  (!( derivadaAux.equalsIgnoreCase(funY))) && !(funY.isBlank()) )
                JOptionPane.showMessageDialog(null, "Error al derivar la función, no son iguales: \nfunY " + funY + " \ny la derivada " + derivadaAux + "\nSe usara funY ingresada.");
            else
                funY = derivadaAux;
            
            PuntoFijoCode lcRaiz = new PuntoFijoCode(xn, tolerancia, funX, funY);
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Punto Fijo:\n"+lcRaiz.calcularRaiz());
            graficarFuncionMetodosAbiertos(funX, funY);
        }
        if(btnChecNewtonRapson.isSelected()){
            derivadaAux = derivacion.derivar(funX);
            if (!( derivadaAux.equalsIgnoreCase(funY) ) ){
                JOptionPane.showMessageDialog(null, "Error al derivar la función, no son iguales funY " + funY + " y la derivada " + derivadaAux + "\nSe usara funY ingresada.");
            }
            NewtonRapsonCode lcRaiz = new NewtonRapsonCode(xn, tolerancia, funX, funY);
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Newton Rapson:\n"+lcRaiz.calcularRaiz());
            graficarFuncionMetodosAbiertos(funX, funY);
        }
        if(btnChecSecante.isSelected()){
            derivadaAux = derivacion.derivar(funX);
            if (!( derivadaAux.equalsIgnoreCase(funY) ) ){
                System.out.println("derivadaAux: "+derivadaAux);
                System.out.println("funY: "+funY);
                JOptionPane.showMessageDialog(null, "Error al derivar la función, no son iguales funY " + funY + " y la derivada " + derivadaAux + "\nSe usara funY ingresada.");
            }
            SecanteCode lcRaiz = new SecanteCode(xn, tolerancia, funX, funY);
            txtAResultados.setText(txtAResultados.getText()+"\n"+"        Secante:\n"+lcRaiz.calcularRaiz());
            graficarFuncionMetodosAbiertos(funX, funY);
        }
        if(!derivadaAux.isBlank() && metodosAbiertos){
            txtFunY.setText(derivadaAux);
            lblInFunF.setForeground(Color.RED); // Cambiar el color del texto a rojo
            lblInFunG.setForeground(Color.BLUE); // Cambiar el color del texto a azul
        }
        
        // TODO Hasta aca llega lo que hay que corregir
        
        btnCalcular.setBackground(Color.green);
        btnVolver.setBackground(Color.green);
        btnCalcular.setEnabled(true);
        btnVolver.setEnabled(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        boolean metodosAbiertos = btnChecPuntoFijo.isSelected() || btnChecNewtonRapson.isSelected() || btnChecSecante.isSelected();
        boolean metodosCerrados = btnChecRegulaFalsi.isSelected()|| btnCheckBiseccion.isSelected();
        if(metodosCerrados){
            a = Double.valueOf(txtVarA.getText());
            b = Double.valueOf(txtVarB.getText());
            graficarFuncionMetodosCerrados();
        }
        if (metodosAbiertos) {
            funX = txtFunF.getText();
            funY = txtFunY.getText();
            a = Double.valueOf(txtVarXNuevo.getText());
            graficarFuncionMetodosAbiertos(funX, funY);
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnChecPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecPuntoFijoActionPerformed
        boolean activo = btnChecPuntoFijo.isSelected() || btnChecNewtonRapson.isSelected() || btnChecSecante.isSelected();
        if(activo){
            txtFunF.setBackground(Color.white);
            txtFunY.setBackground(Color.white);
            txtVarXNuevo.setBackground(Color.white);
            txtVarTol.setBackground(Color.white);
        }else{
            txtFunF.setBackground(Color.gray);
            txtFunY.setBackground(Color.orange);
            txtVarXNuevo.setBackground(Color.orange);
            txtVarTol.setBackground(Color.gray);
        }
        txtFunF.setEnabled(activo);
        txtFunY.setEnabled(activo);
        txtVarXNuevo.setEnabled(activo);
        txtVarTol.setEnabled(activo);
    }//GEN-LAST:event_btnChecPuntoFijoActionPerformed

    private void txtFunYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFunYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFunYActionPerformed

    private void txtFunFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFunFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFunFActionPerformed

    private void btnCheckBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBiseccionActionPerformed
        boolean activo = btnChecRegulaFalsi.isSelected()|| btnCheckBiseccion.isSelected();
        if(activo){
            txtFunF.setBackground(Color.white);
            txtVarA.setBackground(Color.white);
            txtVarB.setBackground(Color.white);
            txtVarTol.setBackground(Color.white);
        }else{
            txtFunF.setBackground(Color.gray);
            txtVarA.setBackground(Color.blue);
            txtVarB.setBackground(Color.blue);
            txtVarTol.setBackground(Color.gray);
        }
        txtFunF.setEnabled(activo);
        txtVarA.setEnabled(activo);
        txtVarB.setEnabled(activo);
        txtVarTol.setEnabled(activo);
    }//GEN-LAST:event_btnCheckBiseccionActionPerformed

    private void btnChecRegulaFalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecRegulaFalsiActionPerformed
        boolean activo = btnChecRegulaFalsi.isSelected()|| btnCheckBiseccion.isSelected();
        if(activo){
            txtFunF.setBackground(Color.white);
            txtVarA.setBackground(Color.white);
            txtVarB.setBackground(Color.white);
            txtVarTol.setBackground(Color.white);
        }else{
            txtFunF.setBackground(Color.gray);
            txtVarA.setBackground(Color.blue);
            txtVarB.setBackground(Color.blue);
            txtVarTol.setBackground(Color.gray);
        }
        txtFunF.setEnabled(activo);
        txtVarA.setEnabled(activo);
        txtVarB.setEnabled(activo);
        txtVarTol.setEnabled(activo);
    }//GEN-LAST:event_btnChecRegulaFalsiActionPerformed

    private void btnChecNewtonRapsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecNewtonRapsonActionPerformed
        boolean activo = btnChecPuntoFijo.isSelected() || btnChecNewtonRapson.isSelected() || btnChecSecante.isSelected();
        if(activo){
            txtFunF.setBackground(Color.white);
            txtFunY.setBackground(Color.white);
            txtVarXNuevo.setBackground(Color.white);
            txtVarTol.setBackground(Color.white);
        }else{
            txtFunF.setBackground(Color.gray);
            txtFunY.setBackground(Color.orange);
            txtVarXNuevo.setBackground(Color.orange);
            txtVarTol.setBackground(Color.gray);
        }
        txtFunF.setEnabled(activo);
        txtFunY.setEnabled(activo);
        txtVarXNuevo.setEnabled(activo);
        txtVarTol.setEnabled(activo);
    }//GEN-LAST:event_btnChecNewtonRapsonActionPerformed

    private void btnChecSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecSecanteActionPerformed
        boolean activo = btnChecPuntoFijo.isSelected() || btnChecNewtonRapson.isSelected() || btnChecSecante.isSelected();
        if(activo){
            txtFunF.setBackground(Color.white);
            txtFunY.setBackground(Color.white);
            txtVarXNuevo.setBackground(Color.white);
            txtVarTol.setBackground(Color.white);
        }else{
            txtFunF.setBackground(Color.gray);
            txtFunY.setBackground(Color.orange);
            txtVarXNuevo.setBackground(Color.orange);
            txtVarTol.setBackground(Color.gray);
        }
        txtFunF.setEnabled(activo);
        txtFunY.setEnabled(activo);
        txtVarXNuevo.setEnabled(activo);
        txtVarTol.setEnabled(activo);
    }//GEN-LAST:event_btnChecSecanteActionPerformed
        
    private void graficarFuncionMetodosCerrados() {
        String funcion = txtFunF.getText();
        ChartPanel chartPanel = Graficador.createChartPanelSimple(funcion);

        // Obtener el chart del chartPanel
        JFreeChart chart = chartPanel.getChart();
        XYPlot plot = (XYPlot) chart.getPlot();

        // Configurar los límites del eje X
        NumberAxis domainAxis = (NumberAxis) plot.getDomainAxis();
        domainAxis.setRange(a, b);

        // Resaltar los ejes x e y en 0
        plot.setDomainZeroBaselineVisible(true);
        plot.setRangeZeroBaselineVisible(true);

        // Limpiar y agregar el chartPanel al jPGrafico
        jPGrafico.removeAll();
        jPGrafico.setLayout(new BorderLayout());
        jPGrafico.add(chartPanel, BorderLayout.CENTER);
        jPGrafico.revalidate();
        jPGrafico.repaint();
    }
    
    private void graficarFuncionMetodosAbiertos(String funcion1, String funcion2) {
        jPGrafico.removeAll();
        jPGrafico.setLayout(new BorderLayout());

        if (funcion1.isBlank() && !funcion2.isBlank()) {
            ChartPanel chartPanel = Graficador.createChartPanelSimple(funcion2);

            // Obtener el chart del chartPanel
            JFreeChart chart = chartPanel.getChart();
            XYPlot plot = (XYPlot) chart.getPlot();

            // Configurar los límites del eje X
            NumberAxis domainAxis = (NumberAxis) plot.getDomainAxis();
            domainAxis.setRange(a * (-2), a * 2);

            // Resaltar los ejes x e y en 0
            plot.setDomainZeroBaselineVisible(true);
            plot.setRangeZeroBaselineVisible(true);

            // Añadir el chartPanel al jPGrafico
            jPGrafico.add(chartPanel, BorderLayout.CENTER);
        } else if (!funcion1.isBlank() && funcion2.isBlank()) {
            ChartPanel chartPanel = Graficador.createChartPanelSimple(funcion1);

            // Obtener el chart del chartPanel
            JFreeChart chart = chartPanel.getChart();
            XYPlot plot = (XYPlot) chart.getPlot();

            // Configurar los límites del eje X
            NumberAxis domainAxis = (NumberAxis) plot.getDomainAxis();
            domainAxis.setRange(a * (-2), a * 2);

            // Resaltar los ejes x e y en 0
            plot.setDomainZeroBaselineVisible(true);
            plot.setRangeZeroBaselineVisible(true);

            // Añadir el chartPanel al jPGrafico
            jPGrafico.add(chartPanel, BorderLayout.CENTER);
        } else if (!funcion1.isBlank() && !funcion2.isBlank()) {
            ChartPanel chartPanel = Graficador.createChartPanelDoble(funcion1, funcion2, a * (-2), a * 2, paso);

            // Obtener el chart del chartPanel
            JFreeChart chart = chartPanel.getChart();
            XYPlot plot = (XYPlot) chart.getPlot();

            // Resaltar los ejes x e y en 0
            plot.setDomainZeroBaselineVisible(true);
            plot.setRangeZeroBaselineVisible(true);

            // Añadir el chartPanel al jPGrafico
            jPGrafico.add(chartPanel, BorderLayout.CENTER);
        }

        jPGrafico.revalidate();
        jPGrafico.repaint();
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBox btnChecNewtonRapson;
    private javax.swing.JCheckBox btnChecPuntoFijo;
    private javax.swing.JCheckBox btnChecRegulaFalsi;
    private javax.swing.JCheckBox btnChecSecante;
    private javax.swing.JCheckBox btnCheckBiseccion;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPGrafico;
    private javax.swing.JPanel jPInput;
    private javax.swing.JPanel jPPrincial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInFunF;
    private javax.swing.JLabel lblInFunG;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAResultados;
    private javax.swing.JTextField txtFunF;
    private javax.swing.JTextField txtFunY;
    private javax.swing.JTextField txtVarA;
    private javax.swing.JTextField txtVarB;
    private javax.swing.JTextField txtVarTol;
    private javax.swing.JTextField txtVarXNuevo;
    // End of variables declaration//GEN-END:variables
}
