package com.cegb03.metodos.igu.reg;

import com.cegb03.metodos.logica.Regresion.RegoPolinomialCode;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author cegb03
 */
public class RegresionPolinomialFrame extends javax.swing.JFrame {
    
    private Double[][] matrix;
    private Double[][] matrixA;
    
    private int filas = 0;
    private int columnas = 0;
    private int grado;

    /**
     * Creates new form EliminacionGaussianaFrame
     */
    public RegresionPolinomialFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAResultados = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Metodo de Regresion Polinomial");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtAResultados.setEditable(false);
        txtAResultados.setColumns(20);
        txtAResultados.setRows(5);
        jScrollPane1.setViewportView(txtAResultados);

        jLabel2.setText("Ingrese el grado del Polinomio: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrado)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarArchivo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarArchivo)
                    .addComponent(jLabel2)
                    .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
         // Verificar si el campo de grado está vacío
        if (txtGrado.getText().isBlank()) {
            // Mostrar un mensaje de advertencia y no continuar con la operación
            JOptionPane.showMessageDialog(this, "No hay grado definido, se cancelará la operación.");
            return; // Salir del método si el grado no está definido
        }

        // Intentar parsear el grado del campo de texto
        try {
            grado = Integer.parseInt(txtGrado.getText());
        } catch (NumberFormatException e) {
            // Mostrar un mensaje de error si el grado no es un número entero válido
            JOptionPane.showMessageDialog(this, "El grado ingresado no es válido. Debe ser un número entero.");
            return; // Salir del método si el grado no es válido
        }

        // Cargar la matriz desde el archivo seleccionado
        loadMatrixFromFile();

        // Separar la matriz en A y b
        separarMatricesAB();

        // Imprimir la matriz
        printMatrix();

        // Crear una instancia de RegoPolinomialCode y realizar la regresión polinomial
        RegoPolinomialCode rpc = new RegoPolinomialCode(matrix, filas, columnas, grado);
        if (txtAResultados.getText().isBlank()) {
            txtAResultados.setText(imprimir() + "\n" + rpc.regresion()); // Puedes modificar esta línea para otro procesamiento
        } else {
            txtAResultados.setText(txtAResultados.getText() + "\n" + rpc.regresion()); // Puedes modificar esta línea para otro procesamiento
        }

        System.out.println("Fin Eliminación");
    }//GEN-LAST:event_btnCargarArchivoActionPerformed
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    // Método para separar la matriz en A y b
    private void separarMatricesAB(){
        int columns = --columnas; // Reducir el número de columnas en 1
        // Copiar la matriz en matrixA
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columns; j++)
                matrixA[i][j] = matrix[i][j];
            matrixA[i][columns] = matrix[i][columns];
        }
        //imprimir(); // Se puede descomentar si se necesita imprimir la matriz
    }

    // Método para cargar la matriz desde el archivo seleccionado
    private void loadMatrixFromFile() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                readMatrixFromFile(selectedFile);
                if (txtAResultados.getText().isBlank()) {
                    System.out.println("Matriz recuperada:\n" + printMatrix() + "\nFin Matriz recuperada.");
                    txtAResultados.setText(printMatrix()); // Puedes modificar esta línea para otro procesamiento
                } else {
                    txtAResultados.setText(txtAResultados.getText() + "\n" + printMatrix()); // Puedes modificar esta línea para otro procesamiento
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Método para leer la matriz desde el archivo
    private void readMatrixFromFile(File file) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line;
        int rows = 0;
        int cols = 0;
        Double[][] matrizCarga = null;

        // Primer pase para determinar el tamaño de la matriz
        while ((line = br.readLine()) != null) {
            String[] values = line.trim().split("\\s+|,");
            if (matrizCarga == null) {
                cols = values.length;
                matrizCarga = new Double[countLines(file)][cols];
            }
            for (int i = 0; i < cols; i++) {
                matrizCarga[rows][i] = Double.valueOf(values[i]);
            }
            rows++;
        }
        br.close();
        filas = rows;
        columnas = cols;
        this.matrix = new Double[filas][columnas];
        this.matrixA = new Double[filas][columnas];

        for (int i = 0; i < filas; i++)
            System.arraycopy(matrizCarga[i], 0, this.matrix[i], 0, columnas);
    }

    // Método para contar el número de líneas en un archivo
    private int countLines(File file) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(file));
        int lines = 0;
        while (br.readLine() != null) {
            lines++;
        }
        br.close();
        return lines;
    }

    // Método para imprimir la matriz en formato de texto
    private String printMatrix() {
        StringBuilder matriz = new StringBuilder();
        for (Double[] row : matrix) {
            for (Double value : row) {
                matriz.append(value).append(" ");
            }
            matriz.append("\n");
        }
        return matriz.toString();
    }

    // Método para imprimir la matriz A y b separadas
    public String imprimir() {
        StringBuilder matrizImpresa = new StringBuilder();
        matrizImpresa.append("Impresión de matrices A y b separadas\n");
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++)
                matrizImpresa.append(matrixA[i][j]).append(" ");
            matrizImpresa.append("| ").append(matrixA[i][columnas]).append("\n");
        }
        matrizImpresa.append("\n");
        return matrizImpresa.toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAResultados;
    private javax.swing.JTextField txtGrado;
    // End of variables declaration//GEN-END:variables
}
